executable              = LLSigYieldCondor.sh
Universe                = vanilla
+JobFlavour             = "testmatch"
output                  = LLSigYieldCondor.$(ClusterId).$(ProcId).out
error                   = LLSigYieldCondor.$(ClusterId).$(ProcId).err
log                     = LLSigYieldCondor.$(ClusterId).$(ProcId).log
getenv                  = True
should_transfer_files   = YES
when_to_transfer_output = ON_EXIT
transfer_output_files   = LLSigCountDCHist_SR+CR_01_$(ProcId).root, LLSigCountDCHist_SR+CR_02_$(ProcId).root, LLSigCountDCHist_SR+CR_03_$(ProcId).root, LLSigCountDCHist_SR+CR_04_$(ProcId).root, LLSigCountDCHist_SR+CR_05_$(ProcId).root, LLSigCountDCHist_SR+CR_06_$(ProcId).root, LLSigCountDCHist_SR+CR_07_$(ProcId).root, LLSigCountDCHist_SR+CR_08_$(ProcId).root, LLSigCountDCHist_SR+CR_09_$(ProcId).root, LLSigCountDCHist_SR+CR_10_$(ProcId).root
output_destination      = root://eosuser.cern.ch//eos/user/k/kmandal/LLSignalYield/


Proxy_filename = x509up_u43881
Proxy_path = /afs/cern.ch/user/k/kmandal/$(Proxy_filename)
Transfer_Input_Files    = $(Proxy_path), LLSigYieldCondor.sh, CMSSW_14_1_0_pre4.tar.gz
arguments               = $(Proxy_path) $(ClusterId) $(ProcId)
queue 175
